github:
  description: Source of Apache ECharts website
  homepage: https://echarts.apache.org
  labels:
    - echarts
    - apache
    - website

  rulesets:
    - name: "Default Branch Protection"
      type: branch
      branches:
        includes:
          - "~DEFAULT_BRANCH"
          - "release/*"
          - "rel/*"
        excludes: []
      bypass_teams:
        - root
      restrict_deletion: true
      restrict_force_push: true
notifications:
  commits: commits@echarts.apache.org
  pullrequests: commits@echarts.apache.org
  issues: commits@echarts.apache.org
