// Generated by CoffeeScript 1.9.2
define(function(require) {
  var _, exports, helper, template;
  exports = {};
  helper = require('./helper');
  _ = require('lodash');
  template = function(list) {
    return "<ol>" + _.map(list, function(item) {
      return "<li> <a href='javascript:void(0)' data-category='" + item[0] + "'>" + item[1] + "</a> </li>";
    }).join('') + "</ol>";
  };
  exports.init = function(ele, list) {
    var category;
    ele = $(ele);
    category = $(template(list)).appendTo(ele);
    return ele.on('click', 'a', function(event) {
      return helper.hashRoute({
        category: $(this).attr('data-category')
      });
    });
  };
  return exports;
});
