// Generated by CoffeeScript 1.9.2
define(function(require) {
  var _, apiData, apiIndex, exports, layoutEle, mark;
  _ = require('lodash');
  mark = require('./mark_view');
  apiIndex = 0;
  apiData = [];
  layoutEle = null;
  exports = {};
  exports.init = function(ele) {
    layoutEle = $(ele);
    apiData = JSON.parse(require('tpl!../../data/api/index.json'));
    layoutEle.find('div').on('mouseover', '.mark-item', _.debounce(function(event) {
      return console.log(event);
    }, 500));
    return this.go(0);
  };
  exports.prev = function() {
    var prevIndex;
    prevIndex = apiIndex - 1;
    if (prevIndex < 0) {
      if (apiData.length > 0) {
        prevIndex = apiData.length - 1;
      } else {
        prevIndex = 0;
      }
    }
    return this.go(prevIndex);
  };
  exports.next = function() {
    var nextIndex;
    nextIndex = apiIndex + 1;
    if (nextIndex > apiData.length - 1) {
      nextIndex = 0;
    }
    return this.go(nextIndex);
  };
  exports.go = function(index) {
    var chartName, imgPath;
    imgPath = '/docv/data/api/';
    chartName = apiData[apiIndex = index];
    return $.getJSON(imgPath + chartName + '.json', function(data) {
      var layout, marks;
      if (layoutEle != null) {
        layoutEle.find('img').attr({
          src: imgPath + chartName + '.png'
        });
      }
      layout = layoutEle.find('div').html('');
      marks = mark.render(data);
      return $(marks).appendTo(layout);
    });
  };
  return exports;
});
