// Generated by CoffeeScript 1.9.2
define(function(require) {
  var _, exports, mark;
  _ = require('lodash');
  mark = require('./mark_view');
  exports = {};
  exports.init = function(ele, data) {
    var $ele, imgPath, layout, marks;
    imgPath = 'echarts-example/';
    $ele = $(ele);
    $ele.find('img').attr({
      src: imgPath + data.fileName,
      title: data.fileName
    });
    layout = $ele.find('div').html('');
    marks = mark.render(data.data);
    $(marks).appendTo(layout);
    return layout.on('mouseover', '.mark-item', _.debounce(function(event) {
      return console.log(event);
    }, 500));
  };
  return exports;
});
