// Generated by CoffeeScript 1.9.2
define(function(require) {
  var CLZ, SELECTOR, _, exports, helper, lang, template;
  exports = {};
  helper = require('./helper');
  _ = require('lodash');
  lang = require('./lang');
  CLZ = {
    SELECT: 'selected',
    LIST: 'api-category-list'
  };
  SELECTOR = {
    SELECT: '.' + CLZ.SELECT,
    LIST: '.' + CLZ.LIST,
    DATA: 'data-category'
  };
  template = function(list) {
    return "<ol>" + _.map(list, function(item) {
      return "<li> <a href='javascript:void(0)' " + SELECTOR.DATA + "='" + item[0] + "'>" + item[lang.langCode === 'en' ? 2 : 1] + "</a> </li>";
    }).join('') + "</ol>";
  };
  exports.init = function(ele, list) {
    var category, me;
    ele = $(ele);
    category = $(template(list)).appendTo(ele);
    me = this;
    return ele.on('click', 'a', function(event) {
      return me.hashRoute($(this).attr('data-category'));
    });
  };
  exports.hashRoute = function(hash) {
    $(SELECTOR.LIST).find(SELECTOR.SELECT).removeClass(CLZ.SELECT);
    $(SELECTOR.LIST).find("a[" + SELECTOR.DATA + "=" + hash + "]").parent('li').addClass(CLZ.SELECT);
    if (helper.getHashInfo().category !== hash) {
      return helper.hashRoute({
        category: hash
      });
    }
  };
  return exports;
});
